In [8]:
## Part 1

#Load libraries
import awscli
import selenium
import boto3
import pandas as pd
import time
import s3fs
from selenium import webdriver

import os
from io import StringIO


####SCRAPE THE WEBSITE######
###call the webdriver
browser = webdriver.Chrome("C:/Program Files (x86)/chromedriver.exe")

#enter the url path that needs to be accessed by webdriver
browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities.jsp')

<ipython-input-8-af54c1445528>:16: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome("C:/Program Files (x86)/chromedriver.exe")

In [9]:
inputElement = browser.find_element_by_xpath("/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
inputElement.send_keys('0')
inputElement1 = browser.find_element_by_xpath("/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()

#identify the table to scrape
table = browser.find_element_by_css_selector('table.Bordered')

print(table)

<ipython-input-9-d9c65ac05c48>:1: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  inputElement = browser.find_element_by_xpath("/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
<ipython-input-9-d9c65ac05c48>:3: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  inputElement1 = browser.find_element_by_xpath("/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()

<selenium.webdriver.remote.webelement.WebElement (session="39d8634639c5493ec24e99922e782b81", element="ef103143-4304-4932-a74b-cc2e77bf6cd2")>

<ipython-input-9-d9c65ac05c48>:6: DeprecationWarning: find_element_by_css_selector is deprecated. Please use find_element(by=By.CSS_SELECTOR, value=css_selector) instead
  table = browser.find_element_by_css_selector('table.Bordered')

In [10]:
####CREATE DATE FRAME#####
#create empty dataframe
df =[]

#loop through dataframe to export table
for row in table.find_elements_by_css_selector('tr'):
      cols = df.append([cell.text for cell in row.find_elements_by_css_selector('td')])


#update dataframe with header 
df = pd.DataFrame(df, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])
display(df) #let's have a look at the data before cr

C:\Users\suraf\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:502: UserWarning: find_elements_by_css_selector is deprecated. Please use find_elements(by=By.CSS_SELECTOR, value=css_selector) instead
  warnings.warn("find_elements_by_css_selector is deprecated. Please use find_elements(by=By.CSS_SELECTOR, value=css_selector) instead")

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
0,None,None,None,None,None,None
1,"""Forever Captain Poodaman"" The Ahmad Butler Fo...",48-07-16,843800926,NFP,PHILADELPHIA,PA
2,"""Studio 5404"" Inc.",44-39-58,463180470,NFP,MASSAPAQUA,NY
3,"""THEY ARE HAITIAN"" FUND, INC.",20-63-46,300170128,NFP,HUDSON,NY
4,"""Y"" Dive, Inc.",48-45-01,854252095,NFP,SAINT ALBANS,NY
5,(ASMA) American Syrian Multicultural Associati...,42-84-63,273130182,NFP,BROOKLYN,NY
6,#FeedHamburg,48-37-35,854150318,NFP,HAMBURG,NY
7,#HicksStrong Inc.,48-10-48,842612081,NFP,CLIFTON PARK,NY
8,#WalkAway Foundation,47-15-80,832820906,NFP,CARLSBAD,CA
9,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
10,1/20/21 Action Fund,46-99-13,832210730,NFP,SAN FRANCISCO,CA
11,"10/40 Connections, Inc.",45-70-15,621825230,NFP,HIXSON,TN
12,"1000 Feet Project, Inc",45-00-14,473820859,NFP,NEW YORK,NY
13,1000 Islands Hose Haulers,45-38-38,454570241,NFP,CARTHAGE,NY
14,"1004 Foundation, Inc.",45-00-13,463110658,NFP,LONG ISLAND CITY,NY
15,100 BLACK MEN OF LONG ISLAND DEVELOPMENT GROUP...,20-08-47,113617702,NFP,HEMPSTEAD,NY

In [11]:
# remove the blank row 
data = df.drop(labels=0, axis=0)

display(data)

,Organization Name,NY Reg #,EIN,Registrant Type,City,State
1,"""Forever Captain Poodaman"" The Ahmad Butler Fo...",48-07-16,843800926,NFP,PHILADELPHIA,PA
2,"""Studio 5404"" Inc.",44-39-58,463180470,NFP,MASSAPAQUA,NY
3,"""THEY ARE HAITIAN"" FUND, INC.",20-63-46,300170128,NFP,HUDSON,NY
4,"""Y"" Dive, Inc.",48-45-01,854252095,NFP,SAINT ALBANS,NY
5,(ASMA) American Syrian Multicultural Associati...,42-84-63,273130182,NFP,BROOKLYN,NY
6,#FeedHamburg,48-37-35,854150318,NFP,HAMBURG,NY
7,#HicksStrong Inc.,48-10-48,842612081,NFP,CLIFTON PARK,NY
8,#WalkAway Foundation,47-15-80,832820906,NFP,CARLSBAD,CA
9,04/11 10:17 PM test,47-13-95,206256427,NFP,ALBANY,NY
10,1/20/21 Action Fund,46-99-13,832210730,NFP,SAN FRANCISCO,CA
11,"10/40 Connections, Inc.",45-70-15,621825230,NFP,HIXSON,TN
12,"1000 Feet Project, Inc",45-00-14,473820859,NFP,NEW YORK,NY
13,1000 Islands Hose Haulers,45-38-38,454570241,NFP,CARTHAGE,NY
14,"1004 Foundation, Inc.",45-00-13,463110658,NFP,LONG ISLAND CITY,NY
15,100 BLACK MEN OF LONG ISLAND DEVELOPMENT GROUP...,20-08-47,113617702,NFP,HEMPSTEAD,NY

In [23]:
###LOAD THE FILE INTO S3####
# prepare csv file name   
pathname = 'database-updates-m10-assignment/'#specify location of s3:/{my-bucket}/
filenames = f"{pathname}charities-bureau-scrape.csv" #name of the filepath and csv file
datetime = time.strftime("%Y%m%d%H%M%S") #timestamp
filenames3 = "%s%s%s.csv"%(filenames,pathname,datetime) #name of the filepath and csv file

#encoding must be adjusted to accommodate abnormal characters. Use s3fs to write to S3 bucket
byte_encoded_df = df.to_csv(None, index=False).encode() #encodes file as binary
s3 = s3fs.S3FileSystem(anon=False)
with s3.open(filenames, 'wb') as file:
    file.write(byte_encoded_df) #writes byte-encoded file to s3 location

#print success message
print("Successfull uploaded file to location:"+str(filenames3))

Successfull uploaded file to location:database-updates-m10-assignment/charities-bureau-scrape.csvdatabase-updates-m10-assignment/20220410154730.csv

In [ ]:
## Part 2

#Load modules
#!pip install webdriver-manager
import awscli
import boto3
import selenium
import pandas as pd
import time
from time import sleep
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

####SCRAPE THE WEBSITE######
###call the webdriver
s=Service(ChromeDriverManager().install())
browser = webdriver.Chrome(service=s)

#enter the url path that needs to be accessed by webdriver
browser.get('https://www.charitiesnys.com/RegistrySearch/search_charities.jsp')

#identify xpath of location to select element
inputElement = browser.find_element(By.XPATH,"/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[2]/td[2]/input[1]")
inputElement.send_keys('0')
inputElement1 = browser.find_element(By.XPATH,"/html/body/div/div[2]/div/table/tbody/tr/td[2]/div/div/font/font/font/font/font/table/tbody/tr[4]/td/form/table/tbody/tr[10]/td/input[1]").click()
sleep(4) #allow for the page to load by adding a sleep element
#identify the table to scrape
table = browser.find_element(By.CSS_SELECTOR,'table.Bordered')
sleep(1)
#####CREATE DATE FRAME#####
#create empty dataframe
df2 =[]

# Number of pages
num_pages = [1,2,3,4,5,6,7]

# For Loop through all pages
for x in num_pages:
    table = browser.find_element_by_css_selector('table.Bordered')
    
# #loop through dataframe to export table
    
    for row in table.find_elements_by_css_selector('tr'):
        cols = df2.append([cell.text for cell in row.find_elements_by_css_selector('td')])
    
# Pagination
    p = browser.find_element_by_xpath('/html/body/div[2]/div/table/tbody/tr/td[3]/div/div/span[2]/a['+str(x)+']').click()

#update dataframe with header 
df2 = pd.DataFrame(df2, columns = ["Organization Name", "NY Reg #", "EIN" ,"Registrant Type","City","State"])


df3 = pd.DataFrame(df2).dropna().reset_index().drop(['index'], axis=1) 


pd.set_option('display.max_rows', None)

df3

In [ ]:
df3.csv=df.to_csv(index=False, line_terminator='\n')

In [ ]:
bucket = 'database-updates-m10-assignment' 
upload_data = df3.csv
upload_key = "Update-M10-assignment.csv"
file_obj = s3.Bucket(bucket).put_object(Key=upload_key, Body=upload_data)
print(file_obj)